name: Microfrontend Build

on:
  push:
    branches:
      - main
      - staging
      - dev*
      - release/*
      - feature/*
  pull_request:
    branches:
      - main
      - release/*

jobs:
  build-root-project:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: set npm timeout
      run: npm config set fetch-timeout 60000
      
    - name: Install Dependencies and Build root-html-file
      run: |
        cd root-html-file
        npm install --legacy-peer-deps
        
  build-navbar:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
        
    - name: set npm timeout
      run: npm config set fetch-timeout 60000

    - name: Install Dependencies and Build navbar
      run: |
        cd navbar
        npm install --legacy-peer-deps
    # npm run build put on the side for now

    # - name: Test navbar
    #   run: |
    #     cd navbar
    #     npm run test

  build-app1:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
        
    - name: set npm timeout
      run: npm config set fetch-timeout 60000

    - name: Install Dependencies and Build app1
      run: |
        cd app1
        npm install --legacy-peer-deps
      # npm run build put on the side for now

    # - name: Test app1
    #   run: |
    #     cd app1
    #     npm run test

  build-app2:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
        
    - name: set npm timeout
      run: npm config set fetch-timeout 60000

    - name: Install Dependencies and Build app2
      run: |
        cd app2
        npm install --legacy-peer-deps
      # npm run build put on the side for now
        
    # - name: Test app2
    #   run: |
    #     cd app2
    #     npm run test


  build-architecture-application:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
        
    - name: set npm timeout
      run: npm config set fetch-timeout 60000

    - name: Install Dependencies and Build architecture application
      run: |
        cd architecture-application
        npm install --legacy-peer-deps
        npm run build

    # - name: Test architecture application
    #   run: |
    #     cd architecture-application
    #     npm run test
  
  build-getting-started-application:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
        
    - name: set npm timeout
      run: npm config set fetch-timeout 60000

    - name: Install Dependencies and Build Getting started application
      run: |
        cd getting-started-application
        npm install --legacy-peer-deps
        npm run build

    # - name: Test Getting started application
    #   run: |
    #     cd getting-started-application
    #     npm run test

  build-bootstrapping-application:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
        
    - name: set npm timeout
      run: npm config set fetch-timeout 60000

    - name: Install Dependencies and Build bootstrapping application
      run: |
        cd bootstrapping-application
        npm install --legacy-peer-deps
        npm run build

    # - name: Test bootstrapping application
    #   run: |
    #     cd bootstrapping-application
    #     npm run test
